apiVersion: v1
kind: Service
metadata:
  name: commafeed-loadbalancer
  namespace: utility
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8073
      targetPort: 8082
  type: LoadBalancer
  loadBalancerIP: 192.168.99.224
  selector:
    app: commafeed