services:
  app:
    image: snapotter/snapotter:latest
    container_name: snapotter
    ports:
      - 1349:1349
    volumes:
      - ./data:/data:rw
    environment:
      AUTH_ENABLED: true
      DEFAULT_USERNAME: ${DEFAULT_USERNAME}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      STORAGE_MODE: local
    restart: unless-stopped
