version: "3"
volumes:
  data:
    name: grafana_data
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000:3000
    network_mode: bridge
    volumes:
      - data:/var/lib/grafana
    restart: unless-stopped
