apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio
  namespace: media
  labels:
    app: stremio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: stremio
  template:
    metadata:
      labels:
      app: stremio
    spec:
      containers:
      - name: stremio
        image: stremio/server:latest
        ports:
        - containerPort: 11470
        resources:
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
        volumeMounts:
            - mountPath: config
              name: docker
              subPath: stremio
            - mountPath: root/.stremio-server
              name: docker
              subPath: stremio
      volumes:
        - hostPath:
            path: /docker
            type: Directory
          name: docker
      