services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    ports:
      - "5471:5000"
    security_opt:
      - apparmor:unconfined
    volumes:
      - data:/kavita/config
      - /mnt/biblioteka/stripovi:/comics

volumes:
  data:
    name: kavita_data
