version: '3.3'
services:
    kavita:
        container_name: kavita
        ports:
            - 5471:5000
        network_mode: bridge
        volumes: # NFS Directories
            - /docker/kavita:/kavita/config
            - /biblioteka/stripovi:/manga
        restart: always
        image: kizaing/kavita