version: "3.3"
volumes:
  data:
    name: kavita_data
services:
  kavita:
    container_name: kavita
    ports:
      - 5471:5000
    network_mode: bridge
    security_opt:
      - apparmor:unconfined
    volumes:
      - data:/kavita/config
      - /biblioteka/stripovi:/comics
    restart: always
    image: jvmilazz0/kavita:latest
