version: "3.3"
volumes:
  data:
    name: kavita_data
services:
  kavita:
    container_name: kavita
    ports:
      - 5471:5000
    network_mode: bridge
    volumes:
      - data:/kavita/config
      - /biblioteka/stripovi:/manga
    restart: always
    image: kizaing/kavita
