version: "3.3"
services:
  shadowsocks:
    container_name: shadowsocks
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    network_mode: bridge
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=9sy6Xt8Ne
    restart: always
