apiVersion: v1
kind: Service
metadata:
  name: it-tools-loadbalancer
  namespace: utility
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5545
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.99.223
  selector:
    app: it-tools