version: '3.9'
services:  
  db:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: your-user
      POSTGRES_PASSWORD: your-password
    volumes:
      - /etc/docker/postgresql:/var/lib/postgresql/data:rw
    network_mode: host
    restart: always