---
services:
  db:
    container_name: postgresql
    image: postgres:16.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/docker/postgresql:/var/lib/postgresql/data:rw
    restart: always
