version: "3.9"
services:
  db:
    container_name: postgresql
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/docker/postgresql:/var/lib/postgresql/data:rw
    network_mode: host
    restart: always
