apiVersion: v1
kind: Service
metadata:
  name: stremio-lb
  namespace: media
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    app: stremio