apiVersion: v1
kind: Service
metadata:
  name: shlink-loadbalancer
  namespace: utility
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8335
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.99.222
  selector:
    app: shlink