services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - data:/var/lib/grafana

volumes:
  data:
    name: grafana_data
