---
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5678 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    hostname: n8n
    user: 0:0
    security_opt:
      - apparmor:unconfined
    ports:
      - 5678:5678
    network_mode: bridge
    volumes:
      - /etc/docker/n8n/data:/home/node/.n8n:rw
      - /etc/docker/n8n/files:/files:rw
    environment:
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: https://${N8N_HOST}
      GENERIC_TIMEZONE: ${TZ}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_SECURE_COOKIE: true
      TZ: ${TZ}
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: ${DATABASE_URL}
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: ${DATABASE_USER}
      DB_POSTGRESDB_PASSWORD: ${DATABASE_PASS}
    env_file:
      - .env
    restart: always
