version: "3.3"
volumes:
  data:
    name: radarr_data
services:
  radarr:
    container_name: radarr
    ports:
      - 7878:7878
    network_mode: bridge
    environment:
      - TZ=Europe/Zagreb
    volumes:
      - data:/config
      - /media/movies/igrani:/movies
      - /downloads:/downloads
    restart: always
    image: ghcr.io/linuxserver/radarr
