version: '3.9'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
          - 82:80
        volumes:
          - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always