version: '3.9'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
          - 80:80
        volumes:
          - /etc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always