---
services:
  cogentapps:
    container_name: cwgpt
    image: ghcr.io/cogentapps/chat-with-gpt:release
    ports:
      - 5551:3000
    network_mode: bridge
    volumes:
      - /docker/cwgpt:/app/data
    restart: always
