apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: utility
  labels:
    app: it-tools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
      - name: it-tools
        image: corentinth/it-tools
        ports:
        - containerPort: 80
        env:
        - name: BASE_URL
          value: "https://it-tools.kalamiri.com"