version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5961:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/docker/postgres:/var/lib/postgres/data:rw
    restart: always
