---
services:
  app:
    container_name: tubesync
    image: ghcr.io/meeb/tubesync:latest
    mem_limit: 6g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:false
    ports:
      - 4848:4848
    volumes:
      - /docker/tubesync/config:/config:rw
      - /downloads:/downloads:rw
    environment:
      TZ: Europe/Zagreb
      HTTP_USER: ${USER}
      HTTP_PASS: ${PASSWORD}
      PUID: 1026
      PGID: 100
    env_file: .env
    restart: unless-stopped
