---
services:
  reverse-proxy:
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /docker/traefik/config:/etc/traefik
      - /docker/traefik/ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    image: traefik:v2.10
