version: "3"
volumes:
  data:
    name: prometheus_data
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    network_mode: bridge
    volumes:
      - /etc/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - data:/prometheus
    restart: always
