version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    network_mode: bridge
    volumes:
      - /docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/prometheus:/prometheus
    restart: always