version: "3.9"
services:
  bender:
    image: jez500/bender
    ports:
      - 8845:8080
    networks:
      - backend
    volumes:
      - /docker/bender:/app/static
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
