version: "3.9"
services:
  bender:
    container_name: bender
    image: jez500/bender
    ports:
      - 8845:8080
    volumes:
      - /docker/bender:/app/static
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
