---
services:
  bender:
    container_name: bender
    image: jez500/bender
    ports:
      - 8845:8080
    network_mode: bridge
    volumes:
      - /mnt/docker/bender:/app/static
    restart: always
