version: "3.9"
services:
  rancher:
    image: rancher/rancher
    container_name: rancher
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /docker/rancher:/var/lib/rancher
    privileged: true
    restart: always
