---
services:
  rancher:
    image: rancher/rancher
    container_name: rancher
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/docker/rancher:/var/lib/rancher
      - /etc/docker/rancher/cni:/var/lib/cni
      - /etc/docker/rancher/kubelet:/var/lib/kubelet
      - /etc/docker/rancher/log:/var/log
    privileged: true
    restart: always
