version: "3.9"
services:
  rancher:
    image: rancher/rancher
    container_name: rancher
    ports:
      - "443:443"
      - "80:80"
    environment:
      - CATTLE_BOOTSTRAP_PASSWORD=eeb3fde0-3e71-4976-b9c1-ca239cec2155
    volumes:
      - /docker/rancher:/var/lib/rancher
      - /docker/rancher/cni:/var/lib/cni
      - /docker/rancher/kubelet:/var/lib/kubelet
      - /docker/rancher/log:/var/log
    privileged: true
    restart: always
