
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stremio-hps
  namespace: media
  labels:
    app: stremio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stremio
  minReplicas:  {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}