apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio
  namespace: media
  labels:
    app: stremio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stremio
  template:
    metadata:
      labels:
        app: stremio
    spec:
      containers:
      - name: stremio
        image: stremio/server:latest
        ports:
        - containerPort: 11470
        resources:
          requests:
            cpu: "50m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "4086Mi"  
        volumeMounts:
            - mountPath: config
              name: docker
              subPath: stremio
            - mountPath: root/.stremio-server
              name: docker
              subPath: stremio
      volumes:
        - hostPath:
            path: /docker
            type: Directory
          name: docker
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            type: stremio
      