apiVersion: v1
kind: Service
metadata:
  name: stremio-loadbalancer
  namespace: media
spec:
  ports:
    - name: http
      protocol: TCP
      port: 11470
      targetPort: 11470
  type: LoadBalancer
  loadBalancerIP: 192.168.99.225
  selector:
    app: stremio