replicaCount: 2

service:
  ports:
    port: 11470
    targetPort: 11470
  loadBalancerIP: 192.168.99.225

resources:
  limits:
    cpu: 1000m
    memory: 4086Mi
  requests:
    cpu: 50m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
  # targetMemoryUtilizationPercentage: 80
