- name: Update Debian and Ubuntu machines
  hosts: all
  become: true
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Clean and remove unused dependency packages
      apt:
        autoclean: true
        autoremove: true
        
    - name: Upgrade all packages
      apt:
        upgrade: 'yes'

    - name: Check if reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required.stat.exists