- name: Update linux machines
  hosts: all
  become: true
  tasks:
    - name: create /var/lib/apt/lists/
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: '0755'
        check_mode: no
    - name: Upgrade all apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Check if Reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required