- name: Update Debian/Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Clean and remove unused dependency packages
      apt:
        autoclean: true
        autoremove: true
        
    - name: Upgrade all packages
      apt:
        upgrade: 'yes'