- name: Update linux machines
  hosts: all
  become: true
  tasks:
    - name: Update packages cache and clean
      apt:
        update_cache: yes
        autoremove: true
        autoclean: true

    - name: Upgrade all packages
      apt:
        upgrade: 'yes'

    - name: Check if Reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required.stat.exists