- name: Update linux machines
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Upgrade all apt packages
      apt:
        update_cache: yes
        autoremove: true
        autoclean: true

    - name: Upgrade all packages on servers
      apt:
      upgrade: 'yes'

    - name: Check if Reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required