- name: Update linux machines
  hosts: all
  become: true
  tasks:
    - name: Upgrade all apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: packages | ensure apt list dir exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
        
    - name: Check if Reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required