- name: Check if reboot is required Debian/Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Check if reboot is required
      become: true
      stat: path=/var/run/reboot-required get_md5=no
      register: reboot_required
    - name: Message if required
      debug:
        reboot-required: "{{ reboot_required.stat.exists }}"