version: "3.3"
services:
  it-tools:
    container_name: it-tools
    ports:
      - 5545:80
    network_mode: bridge
    environment:
      BASE_URL: https://it-tools.home.kalamiri.com
    restart: always
    image: corentinth/it-tools
