---
services:
  it-tools:
    container_name: it-tools
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 5545:80
    network_mode: bridge
    security_opt:
      - apparmor:unconfined
    environment:
      BASE_URL: https://it-tools.kalamiri.com/
    restart: always
    image: corentinth/it-tools
