---
services:
  memcached:
    container_name: cryptgeon-memcached
    image: memcached:1-alpine
    entrypoint: memcached -m 128M -I 4M # Limit to 128 MB Ram, 4M per entry, customize at free will.
  cryptgeon:
    container_name: cryptgeon
    depends_on:
      - memcached
    environment:
      SIZE_LIMIT: 4M
    ports:
      - 8120:5000
    image: cupcakearmy/cryptgeon:latest
