version: "3.3"
volumes:
  data:
    name: postgres_data
services:
  db:
    image: postgres:16
    container_name: semaphore-db
    hostname: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=semaphore
    restart: always
  app:
    container_name: semaphore
    image: semaphoreui/semaphore:latest
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=${DB_USER}
      - SEMAPHORE_DB_PASS=${DB_PASS}
      - SEMAPHORE_DB_HOST=postgres
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME=${ADMIN_NAME}
      - SEMAPHORE_ADMIN_EMAIL=${ADMIN_EMAIL}
      - SEMAPHORE_ADMIN=${ADMIN}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${ACCESS_KEY_ENCRYPTION} # SEMAPHORE_ACCESS_KEY_ENCRYPTION — key for encrypting access keys in database. It must be generated by using the following command: head -c32 /dev/urandom | base64.
      - ANSIBLE_HOST_KEY_CHECKING=false # (optional) change to true if you want to enable host key checking
    restart: always
    depends_on:
      db:
        condition: service_started
