version: '3.3'
volumes:
  data:
    name: postgres_data
services:
  db:
    image: postgres:14
    container_name: semaphore-postgres
    hostname: postgres
    volumes: 
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=yourpass
      - POSTGRES_DB=semaphore
    restart: unless-stopped
  app:
    container_name: semaphore-web
    image: semaphoreui/semaphore:latest
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=user
      - SEMAPHORE_DB_PASS=yourpass
      - SEMAPHORE_DB_HOST=postgres
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=youradminpassword
      - SEMAPHORE_ADMIN_NAME=adminuser
      - SEMAPHORE_ADMIN_EMAIL=admin@example.local
      - SEMAPHORE_ADMIN=adminuser
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=CRx4g4DlNKYasd4Lhys7Av+lBUUT/XWBsdfsJfYznRM= # SEMAPHORE_ACCESS_KEY_ENCRYPTION — key for encrypting access keys in database. It must be generated by using the following command: head -c32 /dev/urandom | base64.
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started