version: '3.3'
services:
    app:
        container_name: emby
        image: emby/embyserver
        ports:
            - 1900:1900
            - 7359:7359
            - 8096:8096
            - 8920:8920
        deploy: # If using Docker Swarm
            restart_policy:
                condition: any
            mode: replicated
            replicas: 5
            placement:
                constraints: [node.role == worker]
            update_config:
                delay: 2s
        devices:
            - /dev/dri:/dev/dri
        environment:
            - UID=1026
            - GID=100
            - TZ=Europe/Zagreb
        volumes:
            - /docker/emby:/config
            - /media/movies/animirani:/animirani
            - /media/movies/dokumentarni:/dokumentarni
            - /media/movies/igrani:/movies
            - /media/tvshows:/tvshows
            - /media/music:/music
            - /media/metube:/metube
            - /media/razno:/razno
            - /backup/emby:/backup
        restart: always