version: '3.3'
volumes:
  data:
    name: emby_data
services:
    app:
        container_name: emby
        image: emby/embyserver
        ports:
            - 1900:1900
            - 7359:7359
            - 8096:8096
            - 8920:8920
        network_mode: bridge
        devices:
            - /dev/dri:/dev/dri
        environment:
            - UID=0
            - GID=0
            - TZ=Europe/Zagreb
        volumes:
            - data:/config
            - /media/movies/animirani:/animirani
            - /media/movies/dokumentarni:/dokumentarni
            - /media/movies/igrani:/movies
            - /media/tvshows:/tvshows
            - /media/music:/music
            - /media/metube:/metube
            - /media/razno:/razno
            - /backup/emby:/backup
        restart: always
        