version: "3.3"
volumes:
  data:
    name: emby_data
services:
  embyserver:
    container_name: emby
    image: emby/embyserver
    ports:
      - 1900:1900
      - 7359:7359
      - 8096:8096
      - 8920:8920
    network_mode: bridge
    devices:
      - /dev/dri:/dev/dri
    environment:
      - UID=1026
      - GID=100
      - TZ=Europe/Zagreb
    volumes:
      - data:/config
      - /mnt/media/movies/animirani:/animirani
      - /mnt/media/movies/dokumentarni:/dokumentarni
      - /mnt/media/movies/igrani:/movies
      - /mnt/media/tvshows:/tvshows
      - /mnt/media/music:/music
      - /mnt/media/metube:/metube
      - /mnt/media/razno:/razno
      - /mnt/C2/emby:/C2
    restart: always
