version: '3.3'
services:
    jackett:
        container_name: jackett
        environment:
            - AUTO_UPDATE=true
            - TZ=Europe/Zagreb
        ports:
            - 9117:9117
        network_mode: bridge
        volumes: # NFS Directories
            - /docker/jackett:/config
            - /volume1/downloads:/downloads
        restart: unless-stopped
        image: ghcr.io/linuxserver/jackett