version: '3.3'
services:
    app:
        container_name: prowlarr
        environment:
            - TZ=Europe/Zagreb
        ports:
            - 9696:9696
        network_mode: bridge
        volumes: # NFS Directories
            - /docker/prowlarr/config:/config
        restart: always
        image: ghcr.io/linuxserver/prowlarr:develop