
version: '3'
services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /docker/bind/config:/etc/bind
      - /docker/bind/cache:/var/cache/bind
      - /docker/bind/records:/var/lib/bind
    environment:
      - BIND9_USER=root
      - TZ=Europe/Zagreb
    restart: unless-stopped