---
services:
  webui:
    image: ollama-webui:latest
    container_name: ollama-webui
    network_mode: bridge
    ports:
      - 3000:8080
    security_opt:
      - no-new-privileges:true
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434/api
