---
volumes:
  data:
    name: gotify_data
services:
  gotify:
    image: ghcr.io/gotify/server:latest
    container_name: gotify
    ports:
      - 6742:80
    network_mode: bridge
    volumes:
      - data:/app/data
    environment:
      TZ: Europe/Zagreb
      GOTIFY_DEFAULTUSER_NAME: username
      GOTIFY_DEFAULTUSER_PASS: changeme
    restart: always
