- name: Mount nfs docker directory
  hosts: all
  become: true
  vars:
    nfsmounts:
      - {  path: "/docker", src: "192.168.99.105:/volume1/docker" }
  tasks:
    - name: Install nfs
      apt:
        name: 
          - nfs-common 
          - nfs-kernel-server
        state: present
        update_cache: true
    - name: Creates directory
      file:
        path: /docker
        state: directory
    - name: mount the nfsshare in client side
      mount:
        fstype: nfs
        opts: defaults
        dump: 0
        passno: 0
        state: mounted
        src: "{{ item.src }}"
        path: "{{ item.path }}"
      with_items: nfsmounts