---
- name: Install docker
  hosts: all
  become: true
  tasks:
    - name: Install docker dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: yes
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
        state: present
    - name: Install docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - python3-docker
        update_cache: yes