- name: Install basic packages
  hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        name:
          - unzip
          - htop
        state: present
        update_cache: true
