- name: Install qemu-guest-agent and start service
  hosts: all
  become: true
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
    - name: Enable service, and not touch the state
      service:
        name: qemu-guest-agent
        enabled: yes
    - name: Start service, if not started
      service:
        name: qemu-guest-agent
        state: started
        