- name: Install qemu-guest-agent and start service
  hosts: all
  become: true
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
    - name: enable services on boot
      ansible.builtin.service:
        name: "qemu-guest-agent"
        enabled: true
        state: started