---
services:
  traefik:
    image: traefik:v3.5.2
    container_name: traefik
    security_opt:
      - no-new-privileges:true # helps to increase security
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8082:8082 # Exposes metrics to host
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_API_EMAIL=${CF_API_EMAIL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/traefik.yaml:ro
      - ./certs:/certs:rw
      - ./config/config.yaml:/config.yaml:ro
      - ./logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reverse-proxy.rule=Host(`reverse-proxy.home.kalamiri.com`)"
      - "traefik.http.routers.reverse-proxy.entrypoints=websecure"
      - "traefik.http.routers.reverse-proxy.service=api@internal"
      - "traefik.http.routers.reverse-proxy.tls=true"
      - "traefik.http.routers.reverse-proxy.tls.certresolver=cloudflare"
    restart: unless-stopped
networks:
  proxy:
    external: true
