services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - "8099:8090"
    volumes:
      - data:/beszel_data

volumes:
  data:
    name: beszel_data
