apiVersion: apps/v1
kind: Deployment
metadata:
  name: bender
  namespace: utility
  labels:
    app: bender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bender
  template:
    metadata:
      labels:
        app: bender
    spec:
      containers:
      - name: bender
        image: jez500/bender
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: app/static
            name: docker
            subPath: bender
      volumes:
        - hostPath:
            path: /docker
            type: Directory
          name: docker