---
volumes:
  data:
    name: bambu-studio_data
services:
  bambustudio:
    image: ghcr.io/linuxserver/bambustudio:latest
    container_name: bambu-studio
    mem_limit: 8g
    cpu_shares: 2048
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    ports:
      - 8233:3000
    volumes:
      - data:/config
    environment:
      DARK_MODE: true #optional
      TZ: Europe/Zagreb
      TITLE: Bambu-Studio
      CUSTOM_USER: ${CUSTOM_USER}
      PASSWORD: ${PASSWORD}
    restart: on-failure:5
