---
services:
  transmission:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 9091:9091
      - 51413:51413/udp
      - 51413:51413
    volumes:
      - /docker/transmission/data:/config
      - /downloads:/downloads
      - /docker/transmission/watch:/watch
    environment:
      TZ: Europe/Zagreb
      USER: <username>
      PASS: <pass>
