apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-loadbalancer
  namespace: longhorn-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    name: http
  type: LoadBalancer
  loadBalancerIP: 192.168.99.249
  selector:
    app: longhorn-ui