version: "3.3"
volumes:
  data:
    name: calibreweb_data
services:
  calibreweb:
    container_name: calibreweb
    ports:
      - 8083:8083
    network_mode: bridge
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=Europe/Zagreb
    volumes:
      - /biblioteka/knjige:/books
    restart: always
    image: ghcr.io/linuxserver/calibre-web
