services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    security_opt:
      - apparmor:unconfined
    environment:
      PUID: 1026
      PGID: 100
      TZ: Europe/Zagreb
    volumes:
      - data:/config
      - /mnt/media/tvshows:/tv
      - /mnt/downloads:/downloads

volumes:
  data:
    name: sonarr_data
