version: "3.3"
volumes:
  data:
    name: sonarr_data
services:
  sonarr:
    container_name: sonarr
    ports:
      - 8989:8989
    network_mode: bridge
    environment:
      - TZ=Europe/Zagreb
    volumes:
      - data:/config
      - /media/tvshows:/tv
      - /downloads:/downloads
    restart: always
    image: ghcr.io/linuxserver/sonarr
