version: "3.3"
volumes:
  data:
    name: sonarr_data
services:
  sonarr:
    container_name: sonarr
    ports:
      - 8989:8989
    network_mode: bridge
    security_opt:
      - apparmor:unconfined
    environment:
      PUID: 1026
      PGID: 100
      TZ: Europe/Zagreb
    volumes:
      - data:/config
      - /mnt/media/tvshows:/tv:rw
      - /mnt/downloads:/downloads:rw
    restart: always
    image: ghcr.io/linuxserver/sonarr
