api:
  dashboard: true
  debug: true
entryPoints:
  web:
    address: ":80"          # HTTP
    http:
      redirections:
        entryPoint:
          to: websecure     # redirect to HTTPS
          scheme: https
          permanent: true   # sends 301 redirect
  websecure:
    address: ":443"         # HTTPS
  metrics:
    address: ":8082"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yaml # example provided gives A+ rating https://www.ssllabs.com/ssltest/
    watch: true
certificatesResolvers:
  cloudflare:
    acme:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging (testing)
      email:  "${CF_API_EMAIL}" # Cloudflare email (or other provider)
      storage: /certs/acme.json
      dnsChallenge:
        provider: cloudflare # change as required
        disablePropagationCheck: true # Some people using Cloudflare note this can solve DNS propagation issues.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
log:
  level: "DEBUG"
  filePath: "/var/log/traefik/traefik.log"
