---
- name: Deploy Watchtower
  hosts: all
  become: yes
  tasks:
  - name: Deploy Watchtower Container
    community.docker.docker_container:
      name: watchtower
      image: containrrr/watchtower
      ports:
        - 8090:8080
      network_mode: bridge
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        - TZ=Europe/Zagreb
        - WATCHTOWER_CLEANUP=true #Removes old images after updating
        - WATCHTOWER_INCLUDE_STOPPED=true #Will also include created and exited containers
        - WATCHTOWER_INCLUDE_RESTARTING=true #Will also include restarting containers.
        - WATCHTOWER_ROLLING_RESTART=true #Restart one image at time instead of stopping and starting all at once
      restart_policy: always
    