---
- name: Deploy portainer-ce latest
  hosts: all
  become: yes
  tasks:
    - name: Create new volume
      community.docker.docker_volume:
        name: portainer_data
    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce"
        ports:
          - 9000:9000
          - 8000:8000
        network_mode: bridge
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        restart_policy: always
