services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    security_opt:
      - apparmor:unconfined
    volumes:
      - data:/config
      - data:/metadata
      - /mnt/biblioteka/audioknjige:/audiobooks

volumes:
  data:
    name: audiobookshelf_data
