---
volumes:
  data:
    name: audiobookshelf_data
services:
  audiobookshelf:
    container_name: audiobookshelf
    ports:
      - 13378:80
    network_mode: bridge
    security_opt:
      - apparmor:unconfined
    volumes:
      - data:/config
      - data:/metadata
      - /mnt/biblioteka/audioknjige:/audiobooks
    restart: always
    image: advplyr/audiobookshelf
