version: "3.9"
services:
  db:
    image: postgres
    container_name: shlink-db
    hostname: shlink-db
    ports:
      - 2665:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "shlink", "-U", "shlinkuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    env_file: .env
