apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media-manager
  labels:
    app: qbittorrent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: ghcr.io/linuxserver/qbittorrent
        ports:
        - containerPort: 8088
          protocol: TCP
        - containerPort: 6881
          protocol: TCP
        - containerPort: 6881
          protocol: UDP
        env:
        - name: WEBUI_PORT
          value: "8088"
        - name: TZ
          value: Europe/Zagreb
        volumeMounts:
          - mountPath: config
            name: docker
            subPath: qbittorrent
          - mountPath: downloads
            name: downloads
            subPath: qbittorrent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 256Mi
      volumes:
        - hostPath:
            path: /docker
            type: Directory
          name: docker
        - hostPath:
            path: /downloads
            type: Directory
          name: downloads