apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qubittorrent-hpa
  namespace: media-manager
  labels:
    app: qbittorrent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qbittorrent
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90