apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-loadbalancer
  namespace: media-manager
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
  type: LoadBalancer
  loadBalancerIP: 192.168.99.224
  selector:
    app: qbittorrent