replicaCount: 3

service:
  ports:
    port: 8088
    targetPort: 8088
  loadBalancerIP: 192.168.99.224

resources:
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
  # targetMemoryUtilizationPercentage: 80