apiVersion: v1
kind: Service
metadata:
  name: flame-loadbalancer
  namespace: utility
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5210
      targetPort: 5005
  type: LoadBalancer
  loadBalancerIP: 192.168.99.221
  selector:
    app: flame