---
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    user: 1000:1000
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=Europe/Zagreb
      - NODE_ENV=production
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=6379
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - UPLOAD_LOCATION=/mnt/homes/sasa/Photos
      - UPLOAD_LOCATION_READONLY=false
      - IMMICH_IGNORE_MOUNT_CHECK_ERRORS=true
    ports:
      - 8212:2283
    network_mode: bridge
    volumes:
      - /etc/docker/immich/upload:/usr/src/app/upload:rw
    restart: always

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-ml
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/docker/immich/upload:/usr/src/app/upload:rw
      - /etc/docker/immich/cache:/cache:rw
      - /etc/docker/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: always
