services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - data:/var/lib/influxdb2
      - /opt/influxdb/config:/etc/influxdb2

volumes:
  data:
    name: influxdb_data
