services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    security_opt:
      - apparmor:unconfined
    environment:
      TZ: Europe/Zagreb
    volumes:
      - data:/config
      - /mnt/media/music:/music
      - /mnt/downloads:/downloads

volumes:
  data:
    name: lidarr_data
