---
volumes:
  data:
    name: jdownloader2_data
services:
  jdownloader-2:
    container_name: jdownloader2
    ports:
      - 3129:3129
      - 5800:5800
      - 5900:5900
    network_mode: bridge
    environment:
      - TZ=Europe/Zagreb
      - VNC_PASSWORD=${VNC_PASSWORD}
    volumes:
      - data:/config
      - data:/output
    restart: unless-stopped
    image: jlesage/jdownloader-2
