---
volumes:
  data:
    name: brave_data
services:
  brave:
    container_name: brave
    image: ghcr.io/linuxserver/brave
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    security_opt:
      - apparmor:unconfined
    shm_size: "2gb"
    restart: on-failure:5
    ports:
      - 3934:3000
    volumes:
      - data:/config
