version: "3.9"
volumes:
  data:
    name: myspeed_data
services:
  myspeed:
    container_name: myspeed
    image: germannewsmaker/myspeed:latest
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - 5216:5216
    volumes:
      - data:/myspeed/data
    environment:
      NODE_ENV: production
