---
volumes:
  data:
    name: mealie_data
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - apparmor:unconfined
    read_only: false
    ports:
      - 9925:9000
    volumes:
      - data:/app/data/
    environment:
      TZ: Europe/Zagreb
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      ALLOW_SIGNUP: true #or false
      BASE_URL: ${BASE_URL}
      DB_ENGINE: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: 443
      POSTGRES_DB: mealie
      # SMTP_HOST: smtp.gmail.com
      # SMTP_PORT: 587
      # SMTP_FROM_NAME: Mealie
      # SMTP_AUTH_STRATEGY: TLS # Options: TLS, SSL, NONE
      # SMTP_FROM_EMAIL: Your-own-gmail-address
      # SMTP_USER: Your-own-gmail-address
      # SMTP_PASSWORD: Your-own-app-password
    env_file:
      - .env
    restart: on-failure:5
