version: "3.3"
volumes:
  data:
    name: bitwarden_data
services:
  server:
    container_name: bitwarden
    ports:
      - 3012:3012
      - 5151:80
    network_mode: bridge
    environment:
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - SIGNUPS_VERIFY=${SIGNUPS_VERIFY}
      - BW_DOMAIN=${BW_DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURITY=${SMTP_SECURITY}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - BW_DB_PROVIDER=${BW_DB_PROVIDER}
      - BW_DB_SERVER=${BW_DB_SERVER}
      - BW_DB_DATABASE=${BW_DB_DATABASE}
      - BW_DB_USERNAME=${BW_DB_USERNAME}
      - BW_DB_PASSWORD=${BW_DB_PASSWORD}
    volumes:
      - data:/data
    restart: always
    image: vaultwarden/server
