version: "3.3"
volumes:
  data:
    name: bitwarden_data
services:
  server:
    container_name: bitwarden
    ports:
      - 80:8080
    network_mode: bridge
    environment:
      - BW_DOMAIN=${BW_DOMAIN}
      - BW_DB_PROVIDER=${BW_DB_PROVIDER}
      - BW_DB_SERVER=${BW_DB_SERVER}
      - BW_DB_DATABASE=${BW_DB_DATABASE}
      - BW_DB_USERNAME=${BW_DB_USERNAME}
      - BW_DB_PASSWORD=${BW_DB_PASSWORD}
      - BW_INSTALLATION_ID=${BW_INSTALLATION_ID}
      - BW_INSTALLATION_KEY=${BW_INSTALLATION_KEY}
      - globalSettings__mail__smtp__host=${SMTP_HOST}
      - globalSettings__mail__smtp__port=${SMTP_PORT}
      - globalSettings__mail__smtp__ssl=true
      - globalSettings__mail__smtp__username=${SMTP_USERNAME}
      - globalSettings__mail__smtp__password=${SMTP_PASSWORD}
      - globalSettings__mail__replyToEmail${SMTP_FROM}
    volumes:
      - data:/etc/bitwarden
    restart: always
    image: bitwarden/self-host:beta
