version: "3.9"
services:
  app:
    image: bizzycolah/qrcode-generator:latest
    container_name: qr-code-generator
    ports:
      - 8895:80
    network_mode: bridge
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5