---
volumes:
  data:
    name: qbittorrent_data
services:
  qbittorrent:
    container_name: qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8088:8088
    network_mode: bridge
    security_opt:
      - apparmor:unconfined
    environment:
      - WEBUI_PORT=8088
      - TZ=Europe/Zagreb
    volumes:
      - data:/config
      - /mnt/downloads:/downloads
    restart: always
    image: ghcr.io/linuxserver/qbittorrent
