---
volumes:
  data:
    name: companioncache
services:
  app:
    image: quay.io/invidious/invidious:master
    container_name: invidious
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    hostname: invidious
    user: 100:100
    security_opt:
      - apparmor:unconfined
    ports:
      - 7601:3000
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: ${DB_NAME}
          user: ${DB_USER}
          password: ${DB_PASSWORD}
          host: ${DB_HOST}
          port: ${DB_PORT}
          check_tables: true
          invidious_companion:
          # URL used for the internal communication between invidious and invidious companion
          # There is no need to change that except if Invidious companion does not run on the same docker compose file.
          - private_url: "http://192.168.99.108:7601"
          # (public) URL used for the communication between your browser and invidious companion
          # IF you are using a reverse proxy OR accessing invidious from an external IP then you NEED to change this value
          # Please consult for more doc: https://github.com/unixfox/invidious/blob/invidious-companion/config/config.example.yml#L57-L88
          # And make sure to add the routes from the post install when using a reverse proxy!
            public_url: ${PUBLIC_URL}
          # IT is NOT recommended to use the same key as HMAC KEY. Generate a new key!
          # Use the key generated in the 2nd step
          invidious_companion_key: ${INVIDIOUS_COMPANION_KEY}
          # external_port:
          # domain:
          # https_only: false
          # statistics_enabled: false
          # Use the key generated in the 2nd step
        hmac_key: ${HMAC_KEY}
    restart: always

  companion:
    container_name: invidious-companion
    image: quay.io/invidious/invidious-companion:latest
    environment:
      # Use the key generated in the 2nd step
      - SERVER_SECRET_KEY=${INVIDIOUS_COMPANION_KEY}
    restart: always
    # Remove "127.0.0.1:" if used from an external IP
    ports:
      - "127.0.0.1:8282:8282"
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    # cache for youtube library
    volumes:
      - data:/var/tmp/youtubei.js:rw
    security_opt:
      - apparmor:unconfined
