---
volumes:
  data:
    name: tubetube_data
services:
  tubetube:
    image: ghcr.io/mattblackonly/tubetube:latest
    container_name: tubetube
    ports:
      - 6543:6543
    security_opt:
      - apparmor:unconfined
    volumes:
      - /mnt/downloads:/data/General:rw
      - /mnt/downloads:/data/Music:rw
      - /mnt/downloads:/data/Podcast:rw
      - /mnt/downloads:/data/Video:rw
      - data:/config:rw
    environment:
      THREAD_COUNT: 1
      PUID: 1026
      PGID: 100
    restart: always
