version: '3.9'
services:
    cloudflared:
      container_name: cloudflared
      command: 'tunnel --no-autoupdate run --token your-token'
      restart: unless-stopped
      image: 'cloudflare/cloudflared:latest'