name: Linux Machines Update

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: "self-hostad"
        steps:
            - name: Checkout
              uses: actions/checkout@2
        