---
volumes:
  data:
    name: spoolman_data
services:
  app:
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    hostname: spoolman
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000/
    ports:
      - 7912:8000
    environment:
      SPOOLMAN_DB_TYPE: postgres
      SPOOLMAN_DB_HOST: ${SPOOLMAN_DB_HOST}
      SPOOLMAN_DB_PORT: 5432
      SPOOLMAN_DB_NAME: ${SPOOLMAN_DB_NAME}
      SPOOLMAN_DB_USERNAME: ${SPOOLMAN_DB_USERNAME}
      SPOOLMAN_DB_PASSWORD: ${SPOOLMAN_DB_PASSWORD}
      TZ: Europe/Zagreb
      FORWARDED_ALLOW_IPS: "*"
      SPOOLMAN_DEBUG_MODE: TRUE
    volumes:
      - data:/home/app/.local/share/spoolman:rw
    restart: unless-stopped
