---
volumes:
  data:
    name: spoolman_data
services:
  app:
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    hostname: spoolman
    security_opt:
      - apparmor:unconfined
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 7912:8000
    network_mode: bridge
    environment:
      SPOOLMAN_DB_TYPE: postgres
      SPOOLMAN_DB_HOST: ${SPOOLMAN_DB_HOST}
      SPOOLMAN_DB_PORT: 5432
      SPOOLMAN_DB_NAME: ${SPOOLMAN_DB_NAME}
      SPOOLMAN_DB_USERNAME: ${SPOOLMAN_DB_USERNAME}
      SPOOLMAN_DB_PASSWORD: ${SPOOLMAN_DB_PASSWORD}
      TZ: Europe/Zagreb
    volumes:
      - data:/home/app/.local/share/spoolman
    restart: unless-stopped
